services:
  app:
    build: .
    ports:
      - "5173:5173"  # Vue app port
      - "3001:3001"  # Express server port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - ./server/.env  # Email credentials
